title: 'IBM HCD + EA BDC Lab'

remote_theme: just-the-docs/just-the-docs
color_scheme: light
plugins:
  - jekyll-remote-theme

url:  https://github.com/Jessmine99
baseurl:  /BDC_Demo

search_enabled: true
heading_anchors: true
nav_enabled: true

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

#Add link to github page  
aux_links:
  BDC Demo on GitHub:
    - https://github.com/Jessmine99/BDC_Demo

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/Jessmine99/BDC_Demo"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"

#Callouts
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
