title: 'IBM HCD + EA BDC Lab'
remote_theme: just-the-docs/just-the-docs

url:  https://github.com/Jessmine99
baseurl:  /BDC_Demo

search_enabled: true
heading_anchors: true
nav_enabled: true

plugins:
  - jekyll-remote-theme
  
aux_links:
  Just the Docs on GitHub:
    - https://github.com/Jessmine99/BDC_Demo

# Show an "On this page" table of contents
toc_enabled: true

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
